### ISSUE TITLE
Service crashes when logs requested from a large file (~1 gb)

### ISSUE THREAD

**Issue by KaustubhDeshmukh** [mkumble/LogMonitorService#23]
Service crashes when logs requested from a large file (~1 gb):

trace:
`/work/submissions/LogMonitorService/src (main ✔) node app.js
2024-02-14T19:05:13.563Z - info: Server is running at http://localhost:3000

<--- Last few GCs --->

[99514:0x138040000]    46943 ms: Mark-sweep 2202.8 (4136.2) -> 2193.2 (4143.0) MB, 297.0 / 0.0 ms  (average mu = 0.589, current mu = 0.019) task; scavenge might not succeed
[99514:0x138040000]    47215 ms: Mark-sweep 2206.9 (4143.0) -> 2197.0 (4150.0) MB, 267.4 / 0.0 ms  (average mu = 0.415, current mu = 0.017) task; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x102ee949c node::Abort() [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 2: 0x102ee968c node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 3: 0x10304226c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 4: 0x1031ed1f8 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 5: 0x1031ebcdc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 6: 0x10326ceb0 v8::internal::ScavengeJob::Task::RunInternal() [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
 7: 0x102f47434 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task>>) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]`

<img width="1297" alt="Screenshot 2024-02-14 at 11 06 25 AM" src="https://github.com/mkumble/LogMonitorService/assets/3673773/71179aaa-d0c1-4326-9794-3bbbac12be03">

**Comment by mkumble** [comment]
Thanks Kaustubh.I see the API fails when converting the huge response to json. I’m reading the file in chunks but I’m loading it to memory when building the response object and then converting to json. I’ll implement streams to pipe the log file input data to the http output response.Best Regards,Mithun On Feb 14, 2024, at 11:09, KaustubhDeshmukh ***@***.***> wrote:﻿
Service crashes when logs requested from a large file (~1 gb):
trace:
`/work/submissions/LogMonitorService/src (main ✔) node app.js
2024-02-14T19:05:13.563Z - info: Server is running at http://localhost:3000
<--- Last few GCs --->
[99514:0x138040000]    46943 ms: Mark-sweep 2202.8 (4136.2) -> 2193.2 (4143.0) MB, 297.0 / 0.0 ms  (average mu = 0.589, current mu = 0.019) task; scavenge might not succeed
[99514:0x138040000]    47215 ms: Mark-sweep 2206.9 (4143.0) -> 2197.0 (4150.0) MB, 267.4 / 0.0 ms  (average mu = 0.415, current mu = 0.017) task; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0x102ee949c node::Abort() [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
2: 0x102ee968c node::ModifyCodeGenerationFromStrings(v8::Localv8::Context, v8::Localv8::Value, bool) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
3: 0x10304226c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
4: 0x1031ed1f8 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
5: 0x1031ebcdc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
6: 0x10326ceb0 v8::internal::ScavengeJob::Task::RunInternal() [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]
7: 0x102f47434 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_deletev8::Task>) [/Users/kaustubh/.nvm/versions/node/v18.15.0/bin/node]`
Screenshot.2024-02-14.at.11.06.25.AM.png (view on web)

**Comment by mkumble** [comment]
Hi Kaustubh, I've updated the code and the tests to read the reverse file as stream. 

I've verified the scenarios with a 10 GB log file. Thanks!
